### ISSUE TITLE
Skipping large build resource

### ISSUE THREAD

**Issue by elidupuis** [percy/ember-percy#15]
I'm running into a an issue with large build resources: `[percy][WARNING] Skipping large build resource:  /assets/vendor.js`.

What's the file size limit internally?  Also, do you have any recommendations for this situation? I'm getting this on our `vendor.js` file so—is our app just too big for Percy?

**Comment by fotinakis** [comment]
That's just a warning, it doesn't actually affect the Percy build. For the ember client in particular, all the JavaScript is evaluated locally in your own test suite and an already-evaluated DOM snapshot is sent up to Percy for rendering—so, JS files are not even required in that case.

That's just a warning because the Percy API has file-size limits for build resources, but it shouldn't affect your builds. Are you seeing something wrong with your builds?

**Comment by elidupuis** [comment]
Our Percy setup is in limbo right now—I meant to ask you this a few weeks ago. We had some other issues in our test suite so Percy isn't actually running right now 😊 . I'll see if I can get things running properly again tomorrow and let you know if I hit any snags.

Thanks for the speedy response!
