### ISSUE TITLE
ember-responsive

### ISSUE THREAD

**Issue by topaxi** [percy/ember-percy#18]
Having responsive diffs is quite awesome!

With [ember-responsive](https://github.com/freshbooks/ember-responsive) or [flexi](https://github.com/html-next/flexi#layouts) one might render different DOM for each device.

Do you have any solution for this scenario in mind?

With `ember-response` it might be quite easy to overwrite the service and do multiple tests/snapshots

**Comment by fotinakis** [comment]
Thanks!

Is there any way to grab the current test breakpoint from `ember-responsive` after using `setBreakpoint('mobile');`? Because you could potentially just customize the name of the percy snapshot to include the breakpoint, like `percySnapshot(`${this.test.fullTitle()} [breakpoint:${breakpoint}]`) or something.
