### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by NullVoxPopuli** [percy/ember-percy#81]
As I'm picking up percy for the first time, I came across this issue: https://github.com/percy/ember-percy/issues/79

which _is_ very important (and related to importing in general), but also, I was wondering, how would I know what I can important, once I guess at the import path?

**Comment by dfreeman** [comment]
It looks like this package already ships an [`index.d.ts`](https://github.com/percy/ember-percy/blob/master/index.d.ts) with a declaration for `percySnapshot` (which as far as I know is the only public interface this addon has).

Unfortunately, calling `percySnapshot(assert)` [as documented](https://docs.percy.io/docs/ember#section-autogenerated-name-for-qunit-tests) isn't compatible with the type declaration, because [the properties it's expecting on QUnit's `assert`](https://github.com/percy/ember-percy/blob/master/index.d.ts#L3-L8) aren't present in its [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7134cfbbb417b81e6a47f8a4b3c14f3b4e46defc/types/qunit/index.d.ts#L8), even though they're present at runtime.

From what I can tell, they're not part of [QUnit's](https://api.qunitjs.com/config/QUnit.assert) or [ember-qunit's](https://github.com/emberjs/ember-qunit) documented API though, so I'm not sure it would make sense to add them to either of those `@types` packages. @mike-north it looks like you're the original author of those declarations—do you have an opinion on the best way to make them reflect reality?

**Comment by mike-north** [comment]
I have no opinion regarding these types, except that had I written them today I would certainly have put some tests in place

**Comment by alexlafroscia** [comment]
I think that this can be closed, given that an `index.d.ts` exists since the `@percy/ember` re-write!

**Comment by Robdel12** [comment]
Looks like this was taken care of in #173 -- thanks @dfreeman 🎉
