### ISSUE TITLE
Can't link my GitHub project

### ISSUE THREAD

**Issue by Turbo87** [percy/ember-percy#90]
I know that this is probably the wrong place to report this, but I couldn't find a contact link on the website and the `percy-web` project seems to have "Issues" disabled.

I was trying to link a project on Percy to the corresponding project on GitHub, but it seems that the website only loads the first ~50 projects from GitHub. Since my GitHub account has a few more projects, the one that I was looking for did not appear in the list and searching for it also did not reveal it. 😢

**Comment by Robdel12** [comment]
Hey Tobias,

Thanks for reaching out! Do you happen to use adblock? We use Intercom for support, so that might've been blocked for you.

This is something we're aware of now -- it looks like we hit a pagination limit on the list of repos and that dropdown is not currently paginated. I'll ping back here when I have more info on a fix 😃

**Comment by timhaines** [comment]
@Turbo87 One quick work around for this is to visit your GitHub settings (on GitHub.com), and update the repos Percy has access to.  Turn off "all repos", and explicitly choose the repos you want to use in Percy.

**Comment by Turbo87** [comment]
Yeah, that worked for now, thanks :)

**Comment by timhaines** [comment]
Thanks Tobias, I'll close this for now, and we'll track this elsewhere.
